export const oidcUserLogsModel = {
  collection: "ext_oidc_user_logs",
  fields: [
    {
      field: "id",
      type: "integer",
      schema: {
        data_type: "integer",
        default_value: "nextval('ext_oidc_settings_id_seq'::regclass)",
        numeric_precision: 32,
        numeric_scale: 0,
        is_unique: true,
        is_primary_key: true,
        has_auto_increment: true,
      },
      meta: {
        field: "id",
        interface: "input",
        readonly: true,
        hidden: true,
        sort: 1,
        width: "full",
      },
    },
    {
      field: "date_created",
      type: "timestamp",
      meta: {
        special: ["date-created"],
        interface: "datetime",
        readonly: true,
        hidden: true,
        width: "full",
        display: "datetime",
        display_options: { relative: true },
      },
      schema: {},
    },
    {
      field: "client_name",
      type: "string",
      schema: {
        data_type: "character varying",
        max_length: 255,
        is_nullable: true,
      },
      meta: {
        field: "client_name",
        interface: "input",
        hidden: false,
        width: "full",
      },
    },
    {
      field: "client_id",
      type: "string",
      schema: {
        data_type: "character varying",
        max_length: 255,
        is_nullable: true,
      },
      meta: {
        field: "client_id",
        interface: "input",
        hidden: false,
        width: "full",
      },
    },
    {
      field: "client_uri",
      type: "string",
      schema: {
        data_type: "text",
        is_nullable: true,
      },
      meta: {
        field: "client_uri",
        interface: "input",
        hidden: false,
        width: "full",
      },
    },
    {
      field: "username",
      type: "string",
      schema: {
        data_type: "character varying",
        max_length: 255,
        is_nullable: true,
      },
      meta: {
        field: "username",
        interface: "input",
        hidden: false,
        width: "full",
      },
    },
    {
      field: "user_id",
      type: "string",
      schema: {
        data_type: "character varying",
        max_length: 255,
        is_nullable: true,
      },
      meta: {
        field: "user_id",
        interface: "input",
        hidden: false,
        width: "full",
      },
    },
    {
      field: "ip",
      type: "string",
      schema: {
        data_type: "character varying",
        max_length: 255,
        is_nullable: true,
      },
      meta: {
        field: "ip",
        interface: "input",
        hidden: false,
        width: "full",
      },
    },
    {
      field: "user_agent",
      type: "string",
      schema: {
        data_type: "text",
        is_nullable: true,
      },
      meta: {
        field: "user_agent",
        interface: "input",
        hidden: false,
        width: "full",
      },
    },
  ],
  meta: {
    collection: "ext_oidc_user_logs",
    hidden: true,
    singleton: false,
    archive_app_filter: true,
    accountability: "all",
    collapse: "open",
    versioning: false,
  },
  schema: {
    schema: "public",
    name: "ext_oidc_user_logs",
  },
};

export const oidcClientModel = {
  collection: "ext_oidc_clients",
  fields: [
    {
      field: "id",
      type: "integer",
      schema: {
        data_type: "integer",
        default_value: "nextval('ext_oidc_settings_id_seq'::regclass)",
        numeric_precision: 32,
        numeric_scale: 0,
        is_unique: true,
        is_primary_key: true,
        has_auto_increment: true,
      },
      meta: {
        field: "id",
        interface: "input",
        readonly: true,
        hidden: true,
        sort: 1,
        width: "full",
      },
    },
    {
      field: "user_created",
      type: "uuid",
      meta: {
        special: ["user-created"],
        interface: "select-dropdown-m2o",
        options: { template: "{{avatar}} {{first_name}} {{last_name}}" },
        display: "user",
        readonly: true,
        hidden: true,
        width: "full",
      },
      schema: {},
    },
    {
      field: "date_created",
      type: "timestamp",
      meta: {
        special: ["date-created"],
        interface: "datetime",
        readonly: true,
        hidden: true,
        width: "full",
        display: "datetime",
        display_options: { relative: true },
      },
      schema: {},
    },
    {
      field: "user_updated",
      type: "uuid",
      meta: {
        special: ["user-updated"],
        interface: "select-dropdown-m2o",
        options: { template: "{{avatar}} {{first_name}} {{last_name}}" },
        display: "user",
        readonly: true,
        hidden: true,
        width: "full",
      },
      schema: {},
    },
    {
      field: "date_updated",
      type: "timestamp",
      meta: {
        special: ["date-updated"],
        interface: "datetime",
        readonly: true,
        hidden: true,
        width: "full",
        display: "datetime",
        display_options: { relative: true },
      },
      schema: {},
    },
    {
      field: "client_name",
      type: "string",
      schema: {
        data_type: "character varying",
        max_length: 255,
        is_nullable: true,
      },
      meta: {
        field: "client_name",
        interface: "input",
        hidden: false,
        width: "full",
        required: true,
      },
    },
    {
      field: "client_site",
      type: "string",
      schema: {
        data_type: "character varying",
        max_length: 255,
        is_nullable: true,
      },
      meta: {
        field: "client_site",
        interface: "input",
        hidden: false,
        width: "full",
        required: true,
      },
    },
    {
      field: "status",
      type: "boolean",
      schema: {
        data_type: "boolean",
        default_value: true,
        is_nullable: true,
      },
      meta: {
        field: "status",
        special: ["cast-boolean"],
        interface: "boolean",
        hidden: false,
        width: "full",
      },
    },
    {
      field: "client_id",
      type: "string",
      schema: {
        data_type: "character varying",
        max_length: 255,
        is_nullable: true,
        is_unique: true,
      },
      meta: {
        field: "client_id",
        interface: "input",
        hidden: false,
        width: "full",
        required: true,
      },
    },
    {
      field: "redirect_uri",
      type: "string",
      schema: {
        data_type: "text",
        is_nullable: true,
      },
      meta: {
        field: "redirect_uri",
        interface: "input",
        hidden: false,
        width: "full",
        required: true,
      },
    },
    {
      field: "client_secret",
      type: "string",
      schema: {
        data_type: "character varying",
        max_length: 255,
        is_nullable: true,
      },
      meta: {
        field: "client_secret",
        interface: "input",
        hidden: false,
        width: "full",
        required: true,
      },
    },
  ],
  meta: {
    collection: "ext_oidc_clients",
    hidden: true,
    singleton: false,
    archive_app_filter: true,
    accountability: "all",
    collapse: "open",
    versioning: false,
  },
  schema: {
    schema: "public",
    name: "ext_oidc_clients",
  },
};
export const oidcSettingsModel = {
  collection: "ext_oidc_settings",
  fields: [
    {
      field: "id",
      type: "integer",
      schema: {
        name: "id",
        data_type: "integer",
        default_value: "nextval('ext_oidc_settings_id_seq'::regclass)",
        numeric_precision: 32,
        numeric_scale: 0,
        is_unique: true,
        is_primary_key: true,
        has_auto_increment: true,
      },
      meta: {
        field: "id",
        interface: "input",
        readonly: true,
        hidden: true,
        sort: 1,
        width: "full",
      },
    },
    {
      field: "user_created",
      type: "uuid",
      meta: {
        special: ["user-created"],
        interface: "select-dropdown-m2o",
        options: { template: "{{avatar}} {{first_name}} {{last_name}}" },
        display: "user",
        readonly: true,
        hidden: true,
        width: "full",
      },
      schema: {},
    },
    {
      field: "date_created",
      type: "timestamp",
      meta: {
        special: ["date-created"],
        interface: "datetime",
        readonly: true,
        hidden: true,
        width: "full",
        display: "datetime",
        display_options: { relative: true },
      },
      schema: {},
    },
    {
      field: "user_updated",
      type: "uuid",
      meta: {
        special: ["user-updated"],
        interface: "select-dropdown-m2o",
        options: { template: "{{avatar}} {{first_name}} {{last_name}}" },
        display: "user",
        readonly: true,
        hidden: true,
        width: "full",
      },
      schema: {},
    },
    {
      field: "date_updated",
      type: "timestamp",
      meta: {
        special: ["date-updated"],
        interface: "datetime",
        readonly: true,
        hidden: true,
        width: "full",
        display: "datetime",
        display_options: { relative: true },
      },
      schema: {},
    },
    {
      field: "issuer",
      type: "text",
      schema: {
        data_type: "text",
        is_nullable: true,
      },
      meta: {
        interface: "input",
        width: "full",
      },
    },
    {
      field: "token_expires_in",
      type: "integer",
      schema: {
        data_type: "integer",
        default_value: 300,
        is_nullable: true,
      },
      meta: {
        interface: "input",
        width: "full",
      },
    },
    {
      field: "refresh_token_expires_in",
      type: "integer",
      schema: {
        data_type: "integer",
        default_value: 86400,
        is_nullable: true,
      },
      meta: {
        interface: "input",
        width: "full",
      },
    },
    {
      field: "allow_refresh_tokens",
      type: "boolean",
      schema: {
        data_type: "boolean",
        is_nullable: true,
      },
      meta: {
        special: ["cast-boolean"],
        interface: "boolean",
        width: "full",
      },
    },
    {
      field: "require_client_secret",
      type: "boolean",
      schema: {
        data_type: "boolean",
        is_nullable: true,
      },
      meta: {
        special: ["cast-boolean"],
        interface: "boolean",
        width: "full",
      },
    },
    {
      field: "publicKeyPem",
      type: "text",
      schema: {
        data_type: "text",
        is_nullable: true,
      },
      meta: {
        interface: "input-code",
        width: "full",
      },
    },
    {
      field: "privateKeyPem",
      type: "text",
      schema: {
        data_type: "text",
        is_nullable: true,
      },
      meta: {
        interface: "input-code",
        width: "full",
      },
    },
    {
      field: "code_expires_in",
      type: "integer",
      schema: {
        data_type: "integer",
        default_value: 300,
        is_nullable: true,
      },
      meta: {
        interface: "input",
        width: "full",
      },
    },
  ],
  meta: {
    collection: "ext_oidc_settings",
    hidden: true,
    singleton: true,
    archive_app_filter: true,
    accountability: "all",
    collapse: "open",
    versioning: false,
  },
  schema: {
    schema: "public",
    name: "ext_oidc_settings",
  },
};
